#!/usr/bin/env bash

# Check if the number of parameters passed is less than 4
if [[ $# -lt 4 ]]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign variables to the parameters passed
path_to_file=$1
server_ip=$2
username=$3
path_to_ssh_key=$4

# Transfer the file using scp with the specified options
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$server_ip:~/"
