#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get -y update
sudo apt-get -y install nginx
file1=/usr/share/nginx/html/index.html
sudo bash -c "echo 'Hello world!' > $file1"
service nginx start
