#!/bin/bash

# Install HAproxy
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAproxy
sudo echo "
global
  log /dev/log local0
  log /dev/log local1 notice
  chroot /var/lib/haproxy
  stats timeout 30s
  user haproxy
  group haproxy

defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000

frontend http
  bind *:80
  default_backend servers

backend servers
  balance roundrobin
  server 82001-web-01 18.209.179.30:80 check
   server 82001-web-02 100.26.232.3:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Start HAproxy
sudo service haproxy start
